BUY_STARS = "buy_stars"
BUY_PREMIUM = "buy_premium"
MY_ORDERS = "my_orders"
SUPPORT = "support"
MAIN_MENU = "main_menu"
ADMIN_MENU = "admin:menu"
ADMIN_LIST_PENDING = "admin:list:pending_review"
ADMIN_LIST_COMPLETED = "admin:list:completed"
ADMIN_LIST_CANCELLED = "admin:list:cancelled"
ADMIN_LIST_ALL = "admin:list:all"

LEGACY_BUY_STARS = "stars:start"
LEGACY_BUY_PREMIUM = "premium:start"
LEGACY_MY_ORDERS = "orders:list"
LEGACY_SUPPORT = "support:start"
LEGACY_MAIN_MENU = "menu:main"
